src/SGM.WebApp/Models/ErrorViewModel.cs
namespace SGM.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SGM.WebApp/Models/UsuarioViewModel.cs
using System.Collections.Generic;

namespace SGM.WebApp.Models
{   
    public class UsuarioLogin
    {    
        public string Email { get; set; }        
        public string Senha { get; set; }
    }

    public class Result<TResult>
    {
        public int StatusCode { get; set; }
        public TResult Data { get; set; }
        public ICollection<string> Errors { get; set; } = new List<string>();
    }

    public class UsuarioRespostaLogin
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string Nome { get; set; }
        public bool Authenticated { get; set; }
        public string Created { get; set; }
        public string Expiration { get; set; }
        public string AccessToken { get; set; }
        public string Role { get; set; }
        public bool IsAdministrador { get; set; }
    }    
}

src/SGM.WebApp/Controllers/ConcertoIluminacaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,Usuario,Funcionário")]
    public class ConcertoIluminacaoController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Cadastro()
        {
            return View();
        }
        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/ConsultaSalarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,Usuario,Funcionário")]
    public class ConsultaSalarioController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/GeoreferenciaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor")]
    public class GeoreferenciaController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/GestaoProjetoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor")]
    public class GestaoProjetoController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/HomeController.cs
using SGM.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,Usuario,Funcionário")]
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SGM.WebApp/Controllers/IsencaoIPTUController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,Usuario,Funcionário")]
    public class IsencaoIPTUController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using SGM.WebApp.Enumerators;
using SGM.WebApp.Models;
using SGM.WebApp.Services;
using System.Threading.Tasks;

namespace SGM.WebApp.Controllers
{    
    public class LoginController : Controller
    {
        private readonly IAutenticacaoService _autenticacaoService;
        public LoginController(IAutenticacaoService autenticacaoService)
        {
            _autenticacaoService = autenticacaoService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("login")]
        public async Task<Result<UsuarioRespostaLogin>> Login([FromBody] UsuarioLogin usuarioLogin)
        {      
            var resposta = await _autenticacaoService.Login(usuarioLogin);
            if (resposta.StatusCode != (int)EStatusCode.OK) return resposta;            

            await _autenticacaoService.RealizarLogin(resposta.Data);
            return resposta;
        }

        [HttpGet]
        [Route("logoff")]
        public async Task<Result<bool>> Logout()
        {
            await _autenticacaoService.Logout();
            return new Result<bool>() { StatusCode = (int)EStatusCode.OK };
        }
    }
}

src/SGM.WebApp/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,Usuario,Funcionário")]
    public class PerfilController : Controller
    {       
        public IActionResult Index(string id)
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/RecuperarSenhaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Route("recuperar-senha")]
    public class RecuperarSenhaController : Controller
    {
        [Route("atualizar-senha")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SGM.WebApp.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/SGM.WebApp/Views/ConcertoIluminacao/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Cadastro de Concerto de Iluminação</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="ConcertoIluminacao" asp-action="Index">Concerto de Iluminação</a></li>
                    <li class="breadcrumb-item active">Cadastrar</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form data-bind="with:solicitacao">
                    <h5 class="mb-3 text-uppercase bg-light p-2"> Detalhes da Solicitação</h5>                   
                    <div class="form-row">
                        <div class="form-group col-md-12">                           
                            <textarea class="form-control" id="observacao" rows="5" data-bind="value: observacao" placeholder="Informe os detalhes da solicitação"></textarea>
                        </div>                       
                    </div>                   

                    <h5 class="mb-3 text-uppercase bg-light p-2"><i class="mdi mdi-home-city mr-1"></i> Informações de Endereço</h5>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="logradouro" class="col-form-label">Logradouro<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="logradouro" data-bind="value: logradouro" placeholder="Informe o logradouro">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="numero" class="col-form-label">Número<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="numero" data-bind="value: numero" placeholder="Informe o número">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="cep" class="col-form-label">CEP<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="cep" maxlength="8" data-bind="value: cep" placeholder="Informe o cep">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="bairro" class="col-form-label">Bairro<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="bairro" data-bind="value: bairro" placeholder="Informe o bairro">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="complemento" class="col-form-label">Complemento</label>
                            <input type="text" class="form-control" id="complemento" data-bind="value: complemento" placeholder="Informe o Complemento">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="estado" class="col-form-label">Estado<span class="text-danger">*</span></label>
                            <select id="estado" class="form-control" data-toggle="select2"
                                    data-bind="value: estadoId, options: $root.estados, optionsText: 'nome', optionsValue: 'estadoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um estado', tags: false }">
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="municipio" class="col-form-label">Município<span class="text-danger">*</span></label>
                            <select id="municipio" class="form-control" data-toggle="select2"
                                    data-bind="value: municipioId, options: $root.municipios, optionsText: 'nome', optionsValue: 'municipioId', valueAllowUnset: true, select2: { placeholder: 'Selecione um município', tags: false }">
                            </select>
                        </div>
                    </div>

                    <div class="form-group float-right">
                        <button type="button" class="btn btn-secondary mr-1" data-bind="click: $parent.voltar">Voltar</button>
                        <button type="button" class="btn btn-primary" data-bind="click: $parent.salvar, disable: $parent.bloqueiaSalvar()">Salvar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {   
    <script src="~/js/concertoIluminacaoCadastro.min.js"></script>
}

src/SGM.WebApp/Views/ConcertoIluminacao/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    <link href="~/css/datatable.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Concerto de Iluminação</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Concerto de Iluminação</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-controller="ConcertoIluminacao" asp-action="Cadastro" class="btn btn-primary waves-effect waves-light mb-3">
                <i class="fa fa-plus-circle mr-1"></i> Novo
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table id="datatable-solicitacao-iluminacao" class="table table-striped dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>Número Solicitacao</th>
                                    <th>Usuário</th>
                                    <th>Data Cadastro</th>
                                    <th>Situação</th>
                                    <th>Opções</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: solicitacoes">
                                <tr>
                                    <td data-bind="text: solicitacaoId"></td>
                                    <td data-bind="text: usuarioNome"></td>
                                    <td data-bind="text: dataCadastro"></td>
                                    <td data-bind="text: situacaoNome"></td>
                                    <td>
                                        <button id="btnIniciarAtendimento" type="button" class="btn btn-secondary waves-effect waves-light" title="Iniciar Atendimento" data-bind="value: solicitacaoId, visible: exibeBotaoIniciarAtendimento()"><i class="mdi mdi-tag-multiple-outline"></i></button>
                                        <button id="btnFinalizarAtendimento" type="button" class="btn btn-success waves-effect waves-light" title="Finalizar Atendimento" data-bind="value: solicitacaoId, visible: exibeBotaoFinalizarAtendimento()"><i class="mdi mdi-check-bold"></i></button>
                                        <button id="btnVisualizar" type="button" class="btn btn-info waves-effect waves-light" title="Visualizar" data-bind="value: solicitacaoId"><i class="mdi mdi-eye-outline"></i></button>
                                        <button id="btnExcluir" type="button" class="btn btn-danger waves-effect waves-light" title="Excluir" data-bind="value: solicitacaoId, visible: exibeBotaoExcluir()"><i class="mdi mdi-trash-can-outline"></i></button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script src="~/js/datatable.min.js"></script>
    <script src="~/js/concertoIluminacao.min.js"></script>
}

src/SGM.WebApp/Views/Georeferencia/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {

}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Georeferência</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Georeferência</li>
                </ol>
            </div>
        </div>
    </div>
</div>


@section scripts {  
    <script src="~/js/georeferencia.min.js"></script>
}

src/SGM.WebApp/Views/GestaoProjeto/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {

}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Gestão Estratégica de Projetos</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Gestão Estratégica de Projetos</li>
                </ol>
            </div>
        </div>
    </div>
</div>


@section scripts {  
    <script src="~/js/gestaoProjeto.min.js"></script>
}

src/SGM.WebApp/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {

}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Home</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Home</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">  
                <h3 class="mb-3 p-2 text-center"> Seja Bem vindo, ao Sistema de Gestão Integrada Municipal - SGM</h3>             
            </div>
        </div>
    </div>
</div>

@section scripts {  
    <script src="~/js/home.min.js"></script>
}

src/SGM.WebApp/Views/IsencaoIPTU/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Solicitação de Isenção IPTU</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="IsencaoIPTU" asp-action="Index">Isenção IPTU</a></li>
                    <li class="breadcrumb-item active">Cadastrar</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form data-bind="with:solicitacao">
                    <h5 class="mb-3 text-uppercase bg-light p-2"> Detalhes da Solicitação</h5>

					<div class="form-row">
						<div class="form-group col-md-6">
							<label for="matricula" class="col-form-label">Matrícula do Imóvel<span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="matricula" data-bind="value: matricula" placeholder="Informe a Matrícula do Imóvel">
						</div>
						@*<div class="form-group col-md-6">
							<label for="anoExercicio" class="col-form-label">Ano do Exercício do IPTU<span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="anoExercicio" data-bind="value: anoExercicio" placeholder="Informe o Ano do Exercício do IPTU">
						</div>*@

					</div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            @* <label for="observacao" class="col-form-label">Observações</label>*@
                            <textarea class="form-control" id="observacao" rows="5" data-bind="value: observacao" placeholder="Informe os detalhes da solicitação"></textarea>
                        </div>
                    </div>

                    <div class="form-group float-right">
                        <button type="button" class="btn btn-secondary mr-1" data-bind="click: $parent.voltar">Voltar</button>
                        <button type="button" class="btn btn-primary" data-bind="click: $parent.salvar, disable: $parent.bloqueiaSalvar()">Salvar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {   
    <script src="~/js/isencaoIPTUCadastro.min.js"></script>
}

src/SGM.WebApp/Views/IsencaoIPTU/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    <link href="~/css/datatable.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Isenção IPTU</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Isenção IPTU</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-controller="IsencaoIPTU" asp-action="Cadastro" class="btn btn-primary waves-effect waves-light mb-3">
                <i class="fa fa-plus-circle mr-1"></i> Novo
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table id="datatable-solicitacao-isencaoIPTU" class="table table-striped dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>Número Solicitacao</th>
                                    <th>Usuário</th>
                                    <th>Matrícula</th>
                                    <th>Data Cadastro</th>
                                    <th>Situação</th>
                                    <th>Opções</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: solicitacoes">
                                <tr>
                                    <td data-bind="text: solicitacaoId"></td>
                                    <td data-bind="text: usuarioNome"></td>
                                    <td data-bind="text: matricula"></td>
                                    <td data-bind="text: dataCadastro"></td>
                                    <td data-bind="text: situacaoNome"></td>
									<td>
										<button id="btnVisualizar" type="button" class="btn btn-info waves-effect waves-light" title="Visualizar" data-bind="value: solicitacaoId"><i class="mdi mdi-eye-outline"></i></button>
									</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script src="~/js/datatable.min.js"></script>
    <script src="~/js/isencaoIPTU.min.js"></script>
}

src/SGM.WebApp/Views/Usuario/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Cadastro de Usuário</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="Usuario" asp-action="Index">Usuários</a></li>
                    <li class="breadcrumb-item active">Cadastrar</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form data-bind="with:usuario">
                    <h5 class="mb-3 text-uppercase bg-light p-2"><i class="mdi mdi-account-circle mr-1"></i> Informações Gerais</h5>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="perfil" class="col-form-label">Perfil<span class="text-danger">*</span></label>
                            <select id="perfil" class="form-control" data-toggle="select2"
                                    data-bind="value: perfil, select2: { placeholder: 'Selecione um perfil', tags: false }">
                                <option value="">Selecione um perfil</option>
                                <option value="Administrador">Administrador</option>
                                <option value="Gestor">Gestor</option>
                                <option value="Usuario">Usuario</option>
                                <option value="Funcionário">Funcionário</option>
                            </select>
                        </div>                      
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="nome" class="col-form-label">Nome<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="nome" data-bind="value: nome" placeholder="Informe o nome">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="email" class="col-form-label">E-mail<span class="text-danger">*</span></label>
                            <input type="email" class="form-control" id="email" data-bind="value: email" placeholder="Informe o e-mail">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="senha" class="col-form-label">Senha<span class="text-danger">*</span></label>
                            <div class="input-group input-group-merge">
                                <input type="password" id="senha" class="form-control" data-bind="value: senha" placeholder="Informe a senha">
                                <div class="input-group-append" data-password="false">
                                    <div class="input-group-text">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="confirmarSenha" class="col-form-label">Confirmar Senha<span class="text-danger">*</span></label>
                            <div class="input-group input-group-merge">
                                <input type="password" id="confirmarSenha" class="form-control" data-bind="value: confirmarSenha" placeholder="Confirme a senha">
                                <div class="input-group-append" data-password="false">
                                    <div class="input-group-text">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="celular" class="col-form-label">Celular<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="celular" maxlength="15" placeholder="Informe o celular"
                                   data-bind="masked: celular, telefone: true" >
                        </div>
                        <div class="form-group col-md-6">
                            <label for="telefone" class="col-form-label">Telefone</label>
                            <input type="text" class="form-control" id="telefone" maxlength="15" placeholder="Informe o telefone"
                                   data-bind="masked: telefone, telefone: true" >
                        </div>
                    </div>

                    <h5 class="mb-3 text-uppercase bg-light p-2"><i class="mdi mdi-home-city mr-1"></i> Informações de Endereço</h5>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="logradouro" class="col-form-label">Logradouro<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="logradouro" data-bind="value: endereco().logradouro" placeholder="Informe o logradouro">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="numero" class="col-form-label">Número<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="numero" data-bind="value: endereco().numero" placeholder="Informe o número">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="cep" class="col-form-label">CEP<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="cep" maxlength="8" data-bind="value: endereco().cep" placeholder="Informe o cep">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="bairro" class="col-form-label">Bairro<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="bairro" data-bind="value: endereco().bairro" placeholder="Informe o bairro">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="complemento" class="col-form-label">Complemento</label>
                            <input type="text" class="form-control" id="complemento" data-bind="value: endereco().complemento" placeholder="Informe o Complemento">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="estado" class="col-form-label">Estado<span class="text-danger">*</span></label>
                            <select id="estado" class="form-control" data-toggle="select2"
                                    data-bind="value: endereco().estadoId, options: $root.estados, optionsText: 'nome', optionsValue: 'estadoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um estado', tags: false }">
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="municipio" class="col-form-label">Município<span class="text-danger">*</span></label>
                            <select id="municipio" class="form-control" data-toggle="select2"
                                    data-bind="value: endereco().municipioId, options: $root.municipios, optionsText: 'nome', optionsValue: 'municipioId', valueAllowUnset: true, select2: { placeholder: 'Selecione um município', tags: false }">
                            </select>
                        </div>
                    </div>

                    <div class="form-group float-right">
                        <button type="button" class="btn btn-secondary mr-1" data-bind="click: $parent.voltar">Voltar</button>
                        <button type="button" class="btn btn-primary" data-bind="click: $parent.salvar, disable: $parent.bloqueiaSalvar()">Salvar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {   
    <script src="~/js/usuarioCadastro.min.js"></script>
}